insert into theatres(theatre_name,location_id) values ('Abirami Theatres',1);
insert into theatres(theatre_name,location_id) values ('Rohini Theatre',1);
insert into theatres(theatre_name,location_id) values ('Marlen Cinemas',1);
insert into theatres(theatre_name,location_id) values ('Sri Ganga Cinemas',1);
insert into theatres(theatre_name,location_id) values ('Yamuna Theatres',1);
insert into theatres(theatre_name,location_id) values ('Jazz Cinemas',1);
insert into theatres(theatre_name,location_id) values ('L A Cinemas',2);
insert into theatres(theatre_name,location_id) values ('Sona Mina Cinemas',2);
insert into theatres(theatre_name,location_id) values ('Megastar Cinemas',2);
insert into theatres(theatre_name,location_id) values ('Mangalam Cinemas',2);
insert into theatres(theatre_name,location_id) values ('Cauvery Cinema Hall',2);
insert into theatres(theatre_name,location_id) values ('Star Cinema Hall',2);
insert into theatres(theatre_name,location_id) values ('Anbu Cinema Hall',2);
insert into theatres(theatre_name,location_id) values ('INOX Cinemas Vishaal De Mal',3);
insert into theatres(theatre_name,location_id) values ('Ambiga Cinemas',3);
insert into theatres(theatre_name,location_id) values ('Cine Priya',3);
insert into theatres(theatre_name,location_id) values ('Guru Cinema Hall',3);
insert into theatres(theatre_name,location_id) values ('Mani Impala Hall',3);
insert into theatres(theatre_name,location_id) values ('Big Cinemas',3);
